name: allagash
channels:
  - esri
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - arcgis=1.6.2
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.6.16
  - cffi=1.12.3
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cryptography=2.7
  - curl=7.65.3
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.2.6
  - fiona=1.8.4
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - gdal=2.3.3
  - geopandas=0.4.1
  - geos=3.7.1
  - giflib=5.1.4
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - importlib_metadata=0.19
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jeepney=0.4
  - jinja2=2.10.1
  - jpeg=9b
  - json-c=0.13.1
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - jupyterlab=1.0.2
  - jupyterlab_server=1.0.0
  - kealib=1.4.7
  - keyring=18.0.0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.65.3
  - libdap4=3.19.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=2.3.3
  - libgfortran-ng=7.3.0
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.16
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - mapclassify=2.0.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - more-itertools=7.2.0
  - munch=2.3.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openjpeg=2.3.0
  - openssl=1.1.1d
  - packaging=19.1
  - pandas=0.25.1
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.2
  - pixman=0.38.0
  - pluggy=0.12.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psycopg2=2.7.6.1
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pyshp=1.2.12
  - pytest=5.0.1
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - rtree=0.8.3
  - scipy=1.3.1
  - secretstorage=3.1.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - sqlalchemy=1.3.7
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - xerces-c=3.2.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.5.2
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - coverage==4.5.4
    - nbval==0.9.2
    - pulp==1.6.10