name: allagash
channels:
  - conda-forge
  - esri
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.13
  - alsa-lib=1.2.8
  - amply=0.1.5
  - anyio=3.6.2
  - arcgis=2.1.0.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - attr=2.5.1
  - attrs=22.2.0
  - aws-c-auth=0.6.26
  - aws-c-cal=0.5.21
  - aws-c-common=0.8.14
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.6
  - aws-c-io=0.13.19
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.7
  - aws-c-sdkutils=0.1.8
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.8
  - aws-sdk-cpp=1.10.57
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.0
  - black=23.1.0
  - bleach=6.0.0
  - blinker=1.5
  - blosc=1.21.3
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - cfitsio=4.2.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - cmarkgfm=0.8.0
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.0.7
  - coverage=7.2.2
  - cryptography=40.0.1
  - curl=7.88.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.3.2
  - dask-core=2023.3.2
  - dbus=1.13.6
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - descartes=1.1.0
  - distlib=0.3.6
  - distributed=2023.3.2
  - docutils=0.18.1
  - entrypoints=0.4
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.10.7
  - fiona=1.9.2
  - flake8=6.0.0
  - flit-core=3.8.0
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.2
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.3.0
  - gdal=3.6.3
  - geomet=1.0.0
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - icu=70.1
  - identify=2.5.22
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.1.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.1.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipykernel=6.22.0
  - ipython=8.11.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.4
  - jack=1.9.22
  - jaraco.classes=3.2.3
  - jedi=0.18.2
  - jeepney=0.8.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - json-c=0.16
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.2
  - jupyter_core=5.3.0
  - jupyter_server=1.23.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.1.3
  - kealib=1.5.0
  - keyring=23.13.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.0
  - libaec=1.0.6
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.88.1
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgdal=3.6.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgoogle-cloud=2.8.0
  - libgpg-error=1.46
  - libgrpc=1.52.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - locket=1.0.0
  - lxml=4.9.2
  - lz4=4.3.2
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=2.0.5
  - more-itertools=9.1.0
  - mpg123=1.31.3
  - msgpack-python=1.0.5
  - munch=2.5.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.8.0
  - nbsphinx=0.9.1
  - nbval=0.9.6
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=3.0
  - nodeenv=1.7.0
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.2
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.1.0
  - orc=1.8.3
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=3.1.1
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.3.0
  - pathspec=0.11.1
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.2.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - poppler=23.03.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - pre-commit=3.2.0
  - proj=9.1.1
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pyflakes=3.0.1
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pykerberos=1.2.4
  - pyopenssl=23.1.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytest=7.2.2
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-gssapi=1.8.2
  - python_abi=3.9
  - pytz=2023.2
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.8
  - qtconsole=5.4.1
  - qtconsole-base=5.4.1
  - qtpy=2.3.0
  - re2=2023.02.02
  - readline=8.2
  - readme_renderer=37.3
  - requests=2.28.2
  - requests-gssapi=1.2.3
  - requests-kerberos=0.12.0
  - requests-oauthlib=1.3.1
  - requests-toolbelt=0.10.1
  - rfc3986=2.0.0
  - rich=13.3.3
  - rtree=1.0.1
  - s2n=1.3.41
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - secretstorage=3.3.3
  - send2trash=1.8.0
  - setuptools=67.6.0
  - shapely=2.0.1
  - sip=6.7.7
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sphinx=6.1.3
  - sphinx_rtd_theme=1.2.0
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.40.0
  - stack_data=0.6.2
  - tblib=1.7.0
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tiledb=2.13.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.9.0
  - twine=4.0.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzcode=2023b
  - tzdata=2023b
  - ucx=1.14.0
  - ujson=5.7.0
  - ukkonen=1.0.1
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - virtualenv=20.21.0
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.40.0
  - widgetsnbextension=3.6.3
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2023.2.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
