name: allagash
channels:
  - esri
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - arcgis=1.8.2
  - argon2-cffi=20.1.0
  - attrs=20.1.0
  - babel=2.8.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.7.22
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.14.2
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cmarkgfm=0.4.2
  - cryptography=3.0
  - curl=7.67.0
  - cycler=0.10.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.9
  - fiona=1.8.13.post1
  - fontconfig=2.13.0
  - freetype=2.10.2
  - freexl=1.0.5
  - future=0.18.2
  - gdal=3.0.2
  - geopandas=0.8.1
  - geos=3.8.0
  - geotiff=1.5.1
  - giflib=5.1.4
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - iniconfig=1.0.1
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jeepney=0.4.3
  - jinja2=2.11.2
  - jpeg=9b
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kealib=1.4.7
  - keyring=21.3.1
  - kiwisolver=1.2.0
  - krb5=1.16.4
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - lerc=2.2
  - libboost=1.67.0
  - libcurl=7.67.0
  - libdap4=3.19.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgdal=3.0.2
  - libgfortran-ng=7.3.0
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.5
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - more-itertools=8.4.0
  - munch=2.5.0
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - conda-forge::nbsphinx=0.7.1
  - ncurses=6.2
  - notebook=6.1.1
  - ntlm-auth=1.5.0
  - numpy=1.19.1
  - numpy-base=1.19.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.1.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.40.0
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - poppler=0.65.0
  - poppler-data=0.4.9
  - postgresql=11.5
  - proj=6.2.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.6
  - prompt_toolkit=3.0.6
  - ptyprocess=0.6.0
  - py=1.9.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pykerberos=1.2.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pyshp=2.1.0
  - pysocks=1.7.1
  - pytest=6.0.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.6
  - qtpy=1.9.0
  - readline=8.0
  - readme_renderer=24.0
  - requests=2.24.0
  - requests-kerberos=0.12.0
  - requests-oauthlib=1.3.0
  - requests-toolbelt=0.9.1
  - requests_ntlm=1.1.0
  - rtree=0.9.4
  - secretstorage=3.1.2
  - send2trash=1.5.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sphinx=3.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.33.0
  - tbb=2018.0.5
  - terminado=0.8.3
  - testpath=0.4.4
  - tiledb=1.6.3
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.48.2
  - traitlets=4.3.3
  - twine=2.0.0
  - tzcode=2020a
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xerces-c=3.2.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - amply==0.1.2
    - coverage==5.2.1
    - nbval==0.9.6
    - pulp==2.3
    - sphinx-rtd-theme==0.4.3