name: allagash
channels:
  - defaults
dependencies:
  - esri::arcgis==1.6.2
  - descartes>=1.1.0
  - shapely==1.6.4
  - geopandas>=0.6.1
  - jupyter>=1.0.0
  - pip>=20.0.2
  - pytest>=5.4.2
  - python>=3.7
  - sphinx>=3.0.3
  - conda-forge::nbsphinx>=0.4.2
  - twine>=2.0.0
  - conda-forge::setuptools>=46.4.0
  - pip:
    - pulp~=2.1
    - sphinx-rtd-theme~=0.4.3
    - nbval~=0.9.5
