name: allagash
channels:
  - conda-forge
  - esri
dependencies:
  - arcgis>=2.1.0.3
  - black>=23.1.0
  - descartes>=1.1.0
  - flake8>=6.0.0
  - geopandas>=0.12.2
  - glpk>=5.0
  - ipywidgets=7.6.0
  - jupyter>=1.0.0
  - nbsphinx>=0.9.1
  - nbval>=0.9.6
  - pandas>=1.5.3
  - pandoc>=3.1.1
  - pip>=23.0.1
  - pre-commit>=3.2.0
  - pytest>=7.2.2
  - python>=3.9
  - pulp>=2.7.0
  - setuptools>=67.6.0
  - shapely>=2.0.1
  - sphinx>=6.1.3
  - sphinx_rtd_theme>=1.2.0
  - twine>=4.0.2
