name: allagash
channels:
  - defaults
  - esri
dependencies:
  - arcgis=1.6.2
  - shapely=1.6.4
  - geopandas=0.4.1
  - jupyter=1.0.0
  - pip>=19.1.1
  - pytest>=5.0.1
  - python=3.7.4
  - sphinx>=2.1
  - conda-forge::nbsphinx>=0.4.2
  - twine>=1.13.0
  - conda-forge::setuptools>=41.2.0
  - pip:
    - pulp==1.6.10
    - sphinx-rtd-theme~=0.4.3
    - nbval~=0.9.2
