name: allagash
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.4.1
  - jupyter=1.0.0
  - pip=19.1.1
  - pytest=5.0.1
  - python=3.7.3
  - sphinx>=2.1
  - nbsphinx>=0.4.2
  - pip:
    - pulp==1.6.10
    - pip sphinx-rtd-theme==0.4.3
