name: allagash
channels:
  - conda-forge
  - esri
dependencies:
  - arcgis>=1.9.1
  - descartes>=1.1.0
  - shapely>=1.8.0
  - geopandas>=0.10.2
  - jupyter>=1.0.0
  - pandoc>=2.16.2
  - pip>=21.3.1
  - pytest>=6.2.5
  - python>=3.8
  - sphinx>=4.3.2
  - nbsphinx>=0.8.7
  - twine>=3.7.1
  - setuptools>=60.1.0
  - pulp>=2.6.0
  - sphinx_rtd_theme>=1.0.0
  - nbval>=0.9.6
