name: allagash
channels:
  - conda-forge
  - esri
dependencies:
  - arcgis>=1.9.1
  - black>=19.10b0
  - descartes>=1.1.0
  - flake8>=4.0.1
  - geopandas>=0.10.2
  - glpk>=5.0
  - jupyter>=1.0.0
  - nbsphinx>=0.8.7
  - nbval>=0.9.6
  - pandoc>=2.16.2
  - pip>=21.3.1
  - pre-commit>=2.16
  - pytest>=6.2.5
  - python>=3.8
  - pulp>=2.6.0
  - shapely>=1.8.0
  - sphinx>=4.3.2
  - sphinx_rtd_theme>=1.0.0
  - tomli>=2.0.0
  - twine>=3.7.1
