name: build

on:
  pull_request:
    branches:
    - develop
    - master
    -
  push:
    branches:
    - develop
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image, build package, install package
      run: docker build . --file build.Dockerfile --tag apulverizer/allagash:build
    - name: Run tests
      run: docker run --user=allagash-user -v $PWD/tests:$PWD/tests -v $PWD/src-doc:$PWD/src-doc -w $PWD apulverizer/allagash:build /bin/bash -c "py.test --nbval"
    - name: Build documentation
      run: docker run --user=allagash-user -v $PWD/src-doc:$PWD/src-doc -v $PWD/docs:$PWD/docs -w $PWD apulverizer/allagash:build /bin/bash -c "pwd && ls -l -a && sphinx-build -b html ./src-doc ./docs -a"
