name: Deploy to PyPi and Docker Hub

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Build docker image, build package, install package
      run: docker build . --file build.Dockerfile -t apulverizer/allagash:build

    - name: Test package
      run: docker run --user=allagash -v $PWD/tests:/home/allagash/tests -v $PWD/src-doc:/home/allagash/src-doc
        apulverizer/allagash:build /bin/bash -c "py.test --nbval"

    - name: Upload to PyPi
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: docker run --user=allagash -w /home/allagash/src apulverizer/allagash:build
        /bin/bash -c "twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*"

    - name: Build public docker image
      run: VERSION=$(docker run --user=allagash apulverizer/allagash:build /bin/bash -c "python src/setup.py --version")
        && docker build . -t apulverizer/allagash:latest -t apulverizer/allagash:$VERSION

    - name: Test docker image
      run: docker run --user=allagash apulverizer/allagash:latest /bin/bash -c "py.test --nbval"

    - name: Deploy to docker hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: VERSION=$(docker run --user=allagash apulverizer/allagash:build /bin/bash -c "python src/setup.py --version")
        && echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        && docker push apulverizer/allagash:$VERSION
        && docker push apulverizer/allagash:latest