name: Deploy to PyPi and Docker Hub

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker image, build package, install package
      run: docker build . --file build.Dockerfile -t apulverizer/allagash:build

    - name: Test package
      run: docker run --user=allagash -v $PWD/tests:/home/allagash/tests -v $PWD/src-doc:/home/allagash/src-doc
        apulverizer/allagash:build /bin/bash -c "py.test --nbval"

    - name: Upload to PyPi
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: docker run --user=allagash -w /home/allagash/src apulverizer/allagash:build
        /bin/bash -c "twine upload -u __token__ -p $PYPI_API_TOKEN dist/*"

    - name: Build public docker image
      run: VERSION=$(docker run --user=allagash apulverizer/allagash:build /bin/bash -c "python -c 'import allagash;print(allagash.__version__)'")
        && docker build --build-arg VERSION=$VERSION . -t apulverizer/allagash:latest -t apulverizer/allagash:$VERSION

    - name: Test docker image
      run: docker run --user=allagash apulverizer/allagash:latest /bin/bash -c "py.test --nbval"

    - name: Deploy to docker hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: VERSION=$(docker run --user=allagash apulverizer/allagash:build /bin/bash -c "python -c 'import allagash;print(allagash.__version__)'")
        && echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        && docker push apulverizer/allagash:$VERSION
        && docker push apulverizer/allagash:latest