name: Docker CI Test

on:
  pull_request:
    branches:
    - develop
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image for testing
      run: docker build . --file Dockerfile --tag apulverizer/allagash:test
    - name: Run tests in docker container
      run: docker run -i -t --user=allagash-user apulverizer/allagash:test /bin/bash -c "py.test --nbval"
    - name: Build documentation
      run: docker run -i -t --user=allagash-user apulverizer/allagash:test /bin/bash -c "sphinx-build -b html ./src-doc ./docs -a"
