name: Docker Image CI

on:
  pull_request:
    branches:
    - develop
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file test.Dockerfile --tag apulverizer/allagash:test
